name: camera_control_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  mocktail: ^1.0.0
  rxdart: ^0.27.7
  xml: ^6.4.2

dev_dependencies:
  lints: ^2.0.0
  freezed: ^2.4.2
  test: ^1.21.0
