name: camera_control_dart
description: Remote control supported Canon EOS cameras.
version: 0.0.1
repository: https://github.com/JulianSchroden/camera_control_dart

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  rxdart: ^0.27.7
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.0
  freezed: ^2.4.2
  mocktail: ^1.0.0
  test: ^1.21.0
