name: camera_control_dart
description: Remote control supported Canon EOS cameras.
version: 0.0.1
repository: https://github.com/JulianSchroden/camera_control_dart

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  xml: ^6.5.0

dev_dependencies:
  args: ^2.5.0
  build_runner: 2.4.11
  lints: ^4.0.0
  freezed: ^2.5.3
  mocktail: ^1.0.4
  test: ^1.25.7
